/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class TelaAula08 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAula08
     */
    public TelaAula08() {
        initComponents();
        lblFala.setText("<html>Pensei em um número inteiro entre 1 e 5. Tente adivinhar.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX = new javax.swing.JLabel();
        lblFala = new javax.swing.JLabel();
        lblBalloon = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        spnrNumber = new javax.swing.JSpinner();
        btnAdivinhar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/charlesXavier.png"))); // NOI18N
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        lblFala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFala.setText("FALA");
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, 80));

        lblBalloon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/balloon.png"))); // NOI18N
        getContentPane().add(lblBalloon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 200, 190));

        lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 0));
        lblText.setText("Número:");
        getContentPane().add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 30));

        spnrNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnrNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnrNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 60, -1));

        btnAdivinhar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdivinhar.setForeground(new java.awt.Color(0, 51, 255));
        btnAdivinhar.setText("Adivinhar");
        btnAdivinhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinharActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinharActionPerformed
        // TODO add your handling code here:
        double n = 1 + Math.random() * (6-1);
        int valorGerado = (int) n;
        
        int valorEscolhido = Integer.parseInt(spnrNumber.getValue().toString());
        
        String fraseAcertou = "Na mosca !";
        String fraseErrou = "Errou. Pensei no número: " + valorGerado;
        
        String resultado = (valorGerado == valorEscolhido) ? fraseAcertou : fraseErrou;
        
        lblFala.setText("<html>" + resultado + "</html>");
    }//GEN-LAST:event_btnAdivinharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinhar;
    private javax.swing.JLabel lblBalloon;
    private javax.swing.JLabel lblFala;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblX;
    private javax.swing.JSpinner spnrNumber;
    // End of variables declaration//GEN-END:variables
}
