
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class TelaBrasileirao2026 extends javax.swing.JFrame {

    String[] times = {
        "América-MG", "Athletic Club", "Atlético-GO", "Avaí", "Botafogo-SP",
        "Ceará", "CRB", "Criciúma", "Cuiabá", "Fortaleza", "Goiás", "Juventude",
        "Londrina", "Náutico", "Novorizontino", "Operário-PR", "Ponte Preta",
        "São Bernardo", "Sport", "Vila Nova"
    };

    DefaultTableModel modeloJogos = new DefaultTableModel(new Object[]{"Local", "", "x", "", "Visitante"}, 0);
    DefaultTableModel modeloClassificacao = new DefaultTableModel(new Object[]{"Time", "P", "V", "E", "D", "GP", "GN", "SG"}, 0);
    
    /**
     * Creates new form TelaBrasileirao2026
     */
    public TelaBrasileirao2026() {
        initComponents();
        configurarLayout();
    }
    
    private void configurarLayout() {
        setTitle("Brasileirão 2026 - Série B - Nicolas de Antoni Mendes");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));


        JPanel painelEsquerda = new JPanel(new BorderLayout());
        JList<String> listaTimesUI = new JList<>(times);
        painelEsquerda.add(new JLabel(" TIMES"), BorderLayout.NORTH);
        painelEsquerda.add(new JScrollPane(listaTimesUI), BorderLayout.CENTER);

        JPanel painelBotoes = new JPanel(new GridLayout(2, 1, 5, 5));
        JButton btnGerar = new JButton("Gerar Campeonato");
        JButton btnLimpar = new JButton("Limpar");
        painelBotoes.add(btnGerar);
        painelBotoes.add(btnLimpar);
        painelEsquerda.add(painelBotoes, BorderLayout.SOUTH);


        JPanel painelCentral = new JPanel(new GridLayout(2, 1, 10, 10));
        JTable tabelaJogos = new JTable(modeloJogos);
        JTable tabelaClassificacao = new JTable(modeloClassificacao);
        painelCentral.add(new JScrollPane(tabelaJogos));
        painelCentral.add(new JScrollPane(tabelaClassificacao));

        add(painelEsquerda, BorderLayout.WEST);
        add(painelCentral, BorderLayout.CENTER);


        btnGerar.addActionListener(e -> gerarCampeonato());
        btnLimpar.addActionListener(e -> {
            modeloJogos.setRowCount(0);
            modeloClassificacao.setRowCount(0);
        });
    }

    private void gerarCampeonato() {
        modeloJogos.setRowCount(0);
        modeloClassificacao.setRowCount(0);
        Random rand = new Random();

        int n = times.length;
        int[] pts = new int[n], vit = new int[n], emp = new int[n];
        int[] der = new int[n], gp = new int[n], gc = new int[n];

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                if (i != j) {
                    int golsC = rand.nextInt(7);
                    int golsF = rand.nextInt(7);
                    modeloJogos.addRow(new Object[]{times[i], golsC, "x", golsF, times[j]});

                    gp[i] += golsC; gc[i] += golsF;
                    gp[j] += golsF; gc[j] += golsC;

                    if (golsC > golsF) { pts[i] += 3; vit[i]++; der[j]++; }
                    else if (golsC < golsF) { pts[j] += 3; vit[j]++; der[i]++; }
                    else { pts[i] += 1; pts[j] += 1; emp[i]++; emp[j]++; }
                }
            }
        }

        Integer[] ordem = new Integer[n];
        for (int i = 0; i < n; i++) ordem[i] = i;

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - 1 - i; j++) {
                if (pts[ordem[j]] < pts[ordem[j + 1]]) {
                    int temp = ordem[j];
                    ordem[j] = ordem[j + 1];
                    ordem[j + 1] = temp;
                }
            }
        }

        for (int i : ordem) {
            modeloClassificacao.addRow(new Object[]{
                times[i], pts[i], vit[i], emp[i], der[i], gp[i], gc[i], (gp[i] - gc[i])
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBrasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBrasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBrasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBrasileirao2026.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBrasileirao2026().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
