/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class TelaAula07 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAula07
     */
    public TelaAula07() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInformarValor = new javax.swing.JLabel();
        spnrValor = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblV1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblV2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblV3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblV4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblV5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 51, 255));
        lblTitle.setText("Super Calculadora");

        lblInformarValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInformarValor.setText("Informe um valor:");

        spnrValor.setModel(new javax.swing.SpinnerNumberModel());

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pngegg.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/344701374_11418820.png"))); // NOI18N

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl1.setText("Resto da Divisão por 2:");

        lblV1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblV1.setText("---");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl2.setText("Elevado ao Cubo:");

        lblV2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblV2.setText("---");

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl3.setText("Raiz Quadrada:");

        lblV3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblV3.setText("---");

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl4.setText("Raiz Cúbica:");

        lblV4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblV4.setText("---");

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl5.setText("Valor Absoluto:");

        lblV5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblV5.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInformarValor)
                        .addGap(18, 18, 18)
                        .addComponent(spnrValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(18, 18, 18)
                        .addComponent(lblV1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(18, 18, 18)
                        .addComponent(lblV2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addGap(18, 18, 18)
                        .addComponent(lblV3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addGap(18, 18, 18)
                        .addComponent(lblV4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl5)
                        .addGap(18, 18, 18)
                        .addComponent(lblV5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInformarValor)
                            .addComponent(spnrValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lblV1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(lblV2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3)
                            .addComponent(lblV3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl4)
                            .addComponent(lblV4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl5)
                            .addComponent(lblV5))
                        .addGap(13, 13, 13))
                    .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int number = Integer.parseInt(spnrValor.getValue().toString());
        int resto = number % 2;
        lblV1.setText(Integer.toString(resto));
        double cubo = number * number * number;
        lblV2.setText(Double.toString(cubo));
        double r2 =  Math.sqrt(number);
        lblV3.setText(Double.toString(r2));
        double r3 = Math.cbrt(number);
        lblV4.setText(Double.toString(r3));
        int abs = Math.abs(number);
        lblV5.setText(Integer.toString(abs));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula07().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInformarValor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblV1;
    private javax.swing.JLabel lblV2;
    private javax.swing.JLabel lblV3;
    private javax.swing.JLabel lblV4;
    private javax.swing.JLabel lblV5;
    private javax.swing.JSpinner spnrValor;
    // End of variables declaration//GEN-END:variables
}
