
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class TelaJogoDaVelhaSwing extends javax.swing.JFrame {

    private JButton[][] botoes = new JButton[3][3];
    private boolean vezDoX = true; // Define quem começa

    public TelaJogoDaVelhaSwing() {
        setTitle("Jogo da Velha");
        setSize(400, 450);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // 1. Criando a Barra de Menu (Arquivo -> Novo/Sair)
        JMenuBar menuBar = new JMenuBar();
        JMenu menuArquivo = new JMenu("Arquivo");
        JMenuItem itemNovo = new JMenuItem("Novo");
        JMenuItem itemSair = new JMenuItem("Sair");

        itemNovo.addActionListener(e -> reiniciarJogo());
        itemSair.addActionListener(e -> System.exit(0));

        menuArquivo.add(itemNovo);
        menuArquivo.add(itemSair);
        menuBar.add(menuArquivo);
        setJMenuBar(menuBar);

        // 2. Painel do Jogo (Grid 3x3)
        JPanel painelJogo = new JPanel(new GridLayout(3, 3, 5, 5));
        inicializarBotoes(painelJogo);
        add(painelJogo, BorderLayout.CENTER);

        setVisible(true);
    }

    private void inicializarBotoes(JPanel painel) {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botoes[i][j] = new JButton("");
                botoes[i][j].setFont(new Font("Arial", Font.BOLD, 60));
                botoes[i][j].setFocusPainted(false);
                
                // Adicionando evento de clique
                final int linha = i;
                final int coluna = j;
                botoes[i][j].addActionListener(e -> realizarJogada(linha, coluna));
                
                painel.add(botoes[i][j]);
            }
        }
    }

    private void realizarJogada(int l, int c) {
        // Só permite jogar se o botão estiver vazio
        if (botoes[l][c].getText().equals("")) {
            botoes[l][c].setText(vezDoX ? "X" : "O");
            botoes[l][c].setForeground(vezDoX ? Color.RED : Color.BLUE);
            
            if (verificarVitoria()) {
                JOptionPane.showMessageDialog(this, "O jogador " + (vezDoX ? "X" : "O") + " venceu!");
                reiniciarJogo();
            } else if (isVelha()) {
                JOptionPane.showMessageDialog(this, "Deu Velha!");
                reiniciarJogo();
            } else {
                vezDoX = !vezDoX; // Alterna o turno
            }
        }
    }

    private boolean verificarVitoria() {
        String p = vezDoX ? "X" : "O";
        
        // Verifica Linhas e Colunas
        for (int i = 0; i < 3; i++) {
            if (botoes[i][0].getText().equals(p) && botoes[i][1].getText().equals(p) && botoes[i][2].getText().equals(p)) return true;
            if (botoes[0][i].getText().equals(p) && botoes[1][i].getText().equals(p) && botoes[2][i].getText().equals(p)) return true;
        }
        
        // Diagonais
        if (botoes[0][0].getText().equals(p) && botoes[1][1].getText().equals(p) && botoes[2][2].getText().equals(p)) return true;
        if (botoes[0][2].getText().equals(p) && botoes[1][1].getText().equals(p) && botoes[2][0].getText().equals(p)) return true;

        return false;
    }

    private boolean isVelha() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (botoes[i][j].getText().equals("")) return false;
            }
        }
        return true;
    }

    private void reiniciarJogo() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botoes[i][j].setText("");
            }
        }
        vezDoX = true;
    }
    
    /**
     * Creates new form TelaJogoDaVelhaSwing
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoDaVelhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoDaVelhaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
